#' confirms choices generated by [add_HSV_range_gui_comp()]
#'
#' @param input - `input` respective shiny-component
#' @param DATA - `DATA` respective shiny-component
#' @param DEBUGKEYS - `DEBUGKEYS` respective shiny-component
#' @param FLAGS - `FLAGS` respective shiny-component
#'
#' @return modified DATA$spectrums
#' @keywords internal
#' @importFrom shiny getDefaultReactiveDomain
#' @importFrom shiny removeModal
#'
submit_added_HSV_range <- function(input, DATA, DEBUGKEYS, FLAGS) {
    new_spectrums <- DATA$spectrums
    adjustments_lower <- c(input$lower_new_H, input$lower_new_S, input$lower_new_V)
    adjustments_upper <- c(input$upper_new_H, input$upper_new_S, input$upper_new_V)
    new_spectrums$lower_bound[[input$added_HSV_range_name]] <- adjustments_lower
    new_spectrums$upper_bound[[input$added_HSV_range_name]] <- adjustments_upper
    changes <- validate_added_HSV_range_values(
        input = input,
        DATA = DATA,
        session = getDefaultReactiveDomain(),
        adjustments_lower,
        adjustments_upper
    )
    DATA$added_spectrum_changes <- changes
    ## assemble the vectors of updated HSV-bounds
    if (length(changes$return_obj)==0) { # just commit the changes (no infringing values were found - all changes were within valid range-limits)
        DATA$spectrums$lower_bound[[input$added_HSV_range_name]] <- adjustments_lower
        DATA$spectrums$upper_bound[[input$added_HSV_range_name]] <- adjustments_upper
        showNotification(
            ui = str_c(
                "Added spectrum '",
                input$added_HSV_range_name,
                "'"
            ),
            type = "message"
        )
        removeModal()
    } else { ## ask the user if the changes are okay?
        ## set values which exceed their bounds to the respective bound
        for (each in names(changes$return_obj)) {
            if (str_count(each,str_c("lower_new"))) {
                if (str_count(each,str_c("new_H"))) {
                    adjustments_lower[[1]] <- changes$return_obj[[each]]
                }
                if (str_count(each,str_c("new_S"))) {
                    adjustments_lower[[2]] <- changes$return_obj[[each]]
                }
                if (str_count(each,str_c("new_V"))) {
                    adjustments_lower[[3]] <- changes$return_obj[[each]]
                }
            }
            if (str_count(each,str_c("upper_new"))) {
                if (str_count(each,str_c("new_H"))) {
                    adjustments_upper[[1]] <- changes$return_obj[[each]]
                }
                if (str_count(each,str_c("new_S"))) {
                    adjustments_upper[[2]] <- changes$return_obj[[each]]
                }
                if (str_count(each,str_c("new_V"))) {
                    adjustments_upper[[3]] <- changes$return_obj[[each]]
                }
            }
        }
        # make a copy to use when confirming the modalDialogue
        DATA$coerced_spectrums <- DATA$spectrums
        # then modify it, so that the changes may be applied.
        DATA$coerced_spectrums$lower_bound[[input$added_HSV_range_name]] <- adjustments_lower
        DATA$coerced_spectrums$upper_bound[[input$added_HSV_range_name]] <- adjustments_upper

        show_infringing_added_spectrum_elements_gui_comp(input, DATA, changes)
    }
    return(new_spectrums)
}
